### ISSUE TITLE
relay certification expires twice a year.

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [freeCodeCamp/coderadio-client#101]
The relay certification expires and requires manual update from the vm:
`./docker.sh update-self
./docker.sh update
`

This should be automated

**Comment by ojeytonwilliams** [comment]
Isn't it using Let's Encrypt?  Renewal should be automatic.

**Comment by ahmadabdolsaheb** [comment]
Yes, there seems to have been an issue with nginx-proxy setup.
It should be working now. I will close this issue now thanks.
