### ISSUE TITLE
The app is consuming high CPU

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/coderadio-client#112]
I checked the CPU consumption using the Task Manager feature on Firefox and found that our app is having very high CPU usage.

Here we have the local version being the most impactful, followed by the prod version. I also opened the Azuracast player for comparison. 

![Screenshot from 2020-12-29 14-50-39](https://user-images.githubusercontent.com/25715018/103268393-f0218880-49e5-11eb-83ca-ae7724756f4d.png)

My hunch is that it has something to do with the AudioContext we are using in the Visualizer component, as it is the most prominent difference between our app and Azuracast's. 

https://github.com/freeCodeCamp/coderadio-client/blob/a151b26a35c44884e9a0f6d69a9bde174713f45a/src/components/Visualizer.js#L34

---

This issue might be related to #80.

**Comment by ahmadabdolsaheb** [comment]
Additionally we could unmount the visualizer when the app in a background tab using libraries such as if visible. serkanyersen.github.io/ifvisible.js/demo.html

**Comment by huyenltnguyen** [comment]
One possibility of the cause is WebSocket connection. Here is what I found from the MDN article about CPU usage and background tabs (https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API#policies_in_place_to_aid_background_page_performance)

> Tabs running code that's using real-time network connections (WebSockets and WebRTC) go unthrottled in order to avoid closing these connections timing out and getting unexpectedly closed.

**Comment by ahmadabdolsaheb** [comment]
After the tab optimizations for the visualization and the footer we are getting around 0.2;
![image](https://user-images.githubusercontent.com/4591597/105580345-e3057880-5d9c-11eb-8486-a6c29538111a.png)

Although removing footer and main components completely lowers cpu usage by 50% on chrome task manager, it barely changes anything on firefox; 

https://github.com/freeCodeCamp/coderadio-client/pull/124
![image](https://user-images.githubusercontent.com/4591597/105580705-07faeb00-5d9f-11eb-83ef-8868bff89066.png)

Might need to go down that route just to make sure we are covering all bases.

**Comment by ahmadabdolsaheb** [comment]
@huyenltnguyen should we close this. It seems like the cpu usage of the production app has been considerably reduced.

**Comment by huyenltnguyen** [comment]
Yeah sure. Thanks for the help!
