### ISSUE TITLE
Desktop does not show relays in the dropdown

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [freeCodeCamp/coderadio-client#14]
comparing the stream list from the embed dropdown and the desktop drop down illustrates the issue.

**Comment by AskMP** [comment]
This is an easy fix. I should be able to add that fairly quickly.

**Comment by AskMP** [comment]
PR submitted. /fcc to see demo

**Comment by ahmadabdolsaheb** [comment]
Thanks
