### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by AskMP** [freeCodeCamp/coderadio-client#19]
There isn't much in the way of text and I'm not suggesting we change all the song names and data but there is content on the page that we can convert into a variety of languages. Small but easy to achieve.

**Comment by xyozio** [comment]
@AskMP I don't think it's worth to implement localization for such content poor app.

@ahmadabdolsaheb Can we close this one?

**Comment by AskMP** [comment]
@xyozio, with such a low hanging fruit as localization for content, I don't see why that wouldn't be something to implement. The original goal for this whole code radio web portal (at least when I originally built it) was to provide a good means for somebody to see the native JavaScript code and how easy things like an audio player seem to be completely forgotten now anyway, so sure. Having a localization addition that users can contribute to and see how easy it can be to add language files to their own projects is kind of mute now anyway. The current dev team has moved this from a couple class files and a simple DOM tree into a react application requiring far more knowledge of JavaScript than somebody just getting into it anyway so I guess there is no reason to have a means of adding simple chooser for users who may not speak English as a first language. [Yes, I'm a bit jaded at the changes but it's not me supporting the tool]
