### ISSUE TITLE
Animation does not appear on firefox

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [freeCodeCamp/coderadio-client#28]
<img width="1226" alt="Screen Shot 2019-08-05 at 12 03 08 PM" src="https://user-images.githubusercontent.com/4591597/62452570-2919e700-b779-11e9-84d1-466e6cc6617d.png">

**Comment by ahmadabdolsaheb** [comment]
most likely we are dealing with vendor prefixes here but needs investigation.

**Comment by huyenltnguyen** [comment]
I'm not sure, but I think this is because the `fastConnection` state is being computed using `navigation.connection` (https://github.com/freeCodeCamp/coderadio-client/blob/master/src/components/App.js#L19), and the property is currently [not supported by Firefox](https://caniuse.com/#feat=netinfo)?

**Comment by ahmadabdolsaheb** [comment]
@huyenltnguyen thanks for looking into this issue.
I ideally we want to find a reliable way to check for the speed and serve content accordingly.
Would you be interested in working on this issue?

**Comment by huyenltnguyen** [comment]
@ahmadabdolsaheb Sure, I'll give this a look 😄 

I'll dig into the web API, see if there is one that we could use cross-browser. But what do you think if we use this package: https://www.npmjs.com/package/speedtest-net?

**Comment by ahmadabdolsaheb** [comment]
@huyenltnguyen Awesome. yeah as long as it is maintained regularly, it is light weight and does not affect our lighthouse performance score negatively.

**Comment by huyenltnguyen** [comment]
@ahmadabdolsaheb Hmm, this is more challenging than I thought.

I've tried out the [speedtest-net](https://www.npmjs.com/package/speedtest-net) package I mentioned above, but unfortunately it doesn't support client-side speed test (https://github.com/ddsol/speedtest.net/issues/66#issuecomment-427382088).

I've also tried using the [network-speed](https://www.npmjs.com/package/network-speed) package, which I thought promising at first, but then found that its calculation is not accurate and unreliable. My result jumped from something like `10 mbps` to `40mbps` just after a refresh. I'm not really familiar with all the web networking, but I guess it has something to do with caching?

Btw, I just noticed that the animation isn't showing up for me on Chrome. I went and checked the `navigation.connection.downlink`, and got around `0.6`, which is way lower than the results from the 2 packages above. I'm not sure this is just me or someone else is having the same issue.

---
Anyway, from my research, there is no reliable option to check the connection speed on the front end, and I think we will need to move it to the server side.

What do you think?

**Comment by ahmadabdolsaheb** [comment]
Thank you for doing the research, @huyenltnguyen.

let's do this:

if mobile-> no animation or office background

if desktop -> yes office background 
also:
- if connection.downlink exist and fast speed = yes anim
-  else no anim
