### ISSUE TITLE
[Enhancement] Separating and Styling Stream Selection Dropdown

### ISSUE THREAD

**Issue by bvi1994** [freeCodeCamp/coderadio-client#288]
I'm wondering if it is worthwhile styling the dropdown to be more consistent with the radio application. I'm also wondering if it's worth separating that logic from the `CurrentSong` component and make its own. 

If that's something that's worth doing, I can do it once I have some free time.

**Comment by ahmadabdolsaheb** [comment]
Thank you for your proposal. Although any incremental improvements are appreciated, we are focusing our efforts into making the listening experience more stable. I highly recommend working on https://github.com/freeCodeCamp/freeCodeCamp/issues/41074 in your free time if you wish to contribute to the coderadio project.
