### ISSUE TITLE
make App.js more modular

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [freeCodeCamp/coderadio-client#29]
Move anything that we can into its own component from the App.js

**Comment by ashwoodall** [comment]
I'd like to tackle this if it isn't already spoken for.

**Comment by ahmadabdolsaheb** [comment]
@ashwoodall thank you for your interest. I would appreciate it if you could take a look into the app.js and see if there is anything that we could turn into a component of its own. If you could not find anything, let us know so we could close this issue accordingly.

**Comment by Ismailtlem** [comment]
Hi,
From what I can see on the render function of the App component, I don't think that there is something that can be put into a separate component (or maybe I am wrong ..)

**Comment by ojeytonwilliams** [comment]
I agree with @Ismailtlem. The App component is looking good now, thanks to @huyenltnguyen's contributions.

If anyone strongly objects, please feel free to reopen this, but I think the issue is resolved.
