### ISSUE TITLE
Play button CTA is a bit misleading

### ISSUE THREAD

**Issue by xyozio** [freeCodeCamp/coderadio-client#31]
When you enter the page the CTA says "Push Play or Space Bar to Start Music". 

The problem is that if the user didn't click the page, the event listener won't fire. So pressing the space bar doesn't work initially.

Maybe the CTA can be changes to "Push Play to Start Music'?

**Comment by vkWeb** [comment]
I think the music should be turned on by default. What do you think @xyozio?

**Comment by xyozio** [comment]
> I think the music should be turned on by default.

I think that it used to auto play and in 035e270 the behavior was changed.

We have to ask @AskMP what he thinks about it.

**Comment by xyozio** [comment]
I think that with the minimal UI that we have right now it's not very difficult to miss the play button.

IMO the call to action can be removed. @huyenltnguyen WDYT?

**Comment by xyozio** [comment]
@ahmadabdolsaheb Can we remove the CTA? I don't think it's really adding any value and it's overlapping the keyboard controls modal.

**Comment by marcosnils** [comment]
https://github.com/freeCodeCamp/coderadio-client/pull/58 > this allows not to click on the window to press the space bar.

**Comment by ahmadabdolsaheb** [comment]
closed by #58
