### ISSUE TITLE
Remove unused files

### ISSUE THREAD

**Issue by xyozio** [freeCodeCamp/coderadio-client#35]
Now after the app was "reactified", can we remove some unused files?

I would like to remove the following ones:

- codeRadio-desktop.js
- codeRadio-mobile.js
- codeRadio.js
- interface.css
- player.js
- visualizer.js

Please let me know if I can open a PR.

**Comment by ahmadabdolsaheb** [comment]
yes we can, and please do, @xyozio   :)
