### ISSUE TITLE
Can't hear any sound on laptop and mobile

### ISSUE THREAD

**Issue by salilmishra23** [freeCodeCamp/coderadio-client#7]
Thanks for launching the radio but I'm unable to hear anything. I tried on Chrome(Version 75.0.3770.100 (Official Build) (64-bit)), Firefox 68.0 (64-bit) and on Andriod mobile running latest Chrome and Brave browsers.

**Comment by AskMP** [comment]
Please, and ignore my ignorance, can you confirm you're pushing play? Chrome and especially mobile require a user interaction to play audio automatically. If you just load the page, it won't play.

**Comment by raisedadead** [comment]
Just throwing this here, because it stuck me after reading your comment:

The progress animation for the radio could be misleading as the music playing, when it's actually not.

So, it makes sense to turn on the progress bar only when the play button is pressed.

**Comment by salilmishra23** [comment]
Thanks, it's working now.

**Comment by raisedadead** [comment]
Thanks for the update. Let us know if you face this again.

**Comment by usersaurus** [comment]
I'm getting this problem too. Google Chrome on Ubuntu 19.04

**Comment by ahmadabdolsaheb** [comment]
@usersaurus, thanks for reporting this issue.
We are working on stability as we speak and we resolved a couple of issues that prevented listeners from tuning in.

I was wondering if you are still experiencing this problem.
If yes, could you try switching the stream on the top left side of the desktop view to an option with (relay 1) at the end and clicking on play button.

**Comment by usersaurus** [comment]
It's working flawlessly now :D Thank you so much.

**Comment by xyozio** [comment]
@ahmadabdolsaheb Should we unpin this one?
